language: ruby
sudo: false
rvm:
  - "2.3.1"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_test;' -U postgres
  - "cp ./config/database.travis.yml ./config/database.yml"
script: bundle exec rake test
notifications:
  email: false